# SPDX-FileCopyrightText: 2026 Mikalai Kaliaha
#
# SPDX-License-Identifier: MIT

"""USB descriptors read off a real DualSense (bcdDevice 0100).

Generated by tools/gen_ds5_usb.py -- do not edit by hand.

These are the bytes a host compares against, so they are served verbatim rather
than rebuilt from fields. Note DEVICE_DESC advertises bNumConfigurations 1 and
iSerial 0: the real controller carries no serial string.

REPORT_DESC is 289 bytes and is NOT the descriptor in ps5_data.py, which comes
from inputtino and is 273 -- the two agree for 145 bytes, then inputtino stops
short of feature reports 0x0B and 0x0C. Prefer this one when impersonating the
device to a host; ps5_data.py remains what the uhid tier uses.
"""

# 18 bytes. Device descriptor: 054c:0ce6, bcdUSB 2.00, class 0 (per-interface).
DEVICE_DESC = bytes.fromhex(
    "12010002000000404c05e60c000101020001"
)

# 227 bytes, wTotalLength 227. The whole configuration in one blob:
#   iface 0    Audio Control     bcdADC 1.00 (UAC1, not UAC2)
#   iface 1/1  Audio Streaming   4ch s16le 48000, EP 0x01 OUT iso ADAPTIVE, 392 B
#   iface 2/1  Audio Streaming   2ch s16le 48000, EP 0x82 IN  iso ASYNC,    196 B
#   iface 3    HID               EP 0x84 IN + EP 0x03 OUT, interrupt, 64 B
# Haptic actuators are the RL/RR pair of wChannelConfig 0x0033, i.e. ch2 and ch3.
CONFIG_DESC = bytes.fromhex(
    "0902e300040100c0fa0904000000010100000a2401000149000201020c240201"
    "01010604330000000c24060201010300000000000924030301030402000c2402"
    "0402040302030000000924060504010300000924030601010105000904010000"
    "01020000090401010101020000072401010101000b2402010402100180bb0009"
    "0501098801040000072501000000000904020000010200000904020101010200"
    "00072401060101000b2402010202100180bb0009058205c40004000007250100"
    "0000000904030002030000000921110100012221010705840340000607050303"
    "400006"
)

# 289 bytes, from /sys/bus/hid/devices/0003:054C:0CE6.*/report_descriptor.
REPORT_DESC = bytes.fromhex(
    "05010905a1018501093009310932093509330934150026ff0075089506810206"
    "00ff09209501810205010939150025073500463b016514750495018142650005"
    "091901290f150025017501950f81020600ff0921950d81020600ff0922150026"
    "ff0075089534810285020923952f9102850509339528b10285080934952fb102"
    "850909249513b102850a0925951ab102850b09419529b102850c09429529b102"
    "85200926953fb102852109279504b10285220940953fb10285800928953fb102"
    "85810929953fb1028582092a9509b1028583092b953fb1028584092c953fb102"
    "8585092d9502b10285a0092e9501b10285e0092f953fb10285f00930953fb102"
    "85f10931953fb10285f20932950fb10285f40935953fb10285f509369503b102"
    "c0"
)

VENDOR_ID = 0x054C
PRODUCT_ID = 0x0CE6

# String descriptors, by index, as the real device reports them.
STRINGS = {
    1: "Sony Interactive Entertainment",
    2: "DualSense Wireless Controller",
}
LANGIDS = (0x0409,)

# Feature reports, read off the same physical controller, WITHOUT the leading
# report id -- whoever serves these prepends it exactly once. inputtino's copies
# in ps5_data.py do include the id, which is a trap: prefixing those shifts every
# byte of calibration data by one and the pad still enumerates.
FEATURE_REPORTS = {
    0x05: bytes.fromhex(
        "00000a00000092226edd8a228add8a2276dd1c021c020320f8dfe51fe7dff21f"
        "e4df0a0000000000"
    ),
    0x09: bytes.fromhex(
        "74e7d63a53350825001e00ee74d0bc00000000"
    ),
    0x0B: bytes.fromhex(
        "74e7d63a5335082500011e00ee74d0bc001e00ee74d0bc000000000000000000"
        "000000000000000000"
    ),
    0x20: bytes.fromhex(
        "4a756c202034203230323531303a33383a343003000b00110800002a00100101"
        "48020000000000000000003006000001000300101003000600000000000000"
    ),
}
