#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Mikalai Kaliaha
#
# SPDX-License-Identifier: MIT

"""Generate flydigi/ps5_data.py from inputtino's ps5.hpp.

The DualSense report descriptor and the canned feature-report blobs
(calibration, pairing info, firmware info) are needed for hid-playstation to
probe a virtual DualSense successfully. Rather than re-derive them we take them
from inputtino, which is MIT licensed.

    python3 tools/gen_ps5_data.py work/ref/inputtino/src/uhid/include/uhid/ps5.hpp
"""
import re
import sys

ARRAYS = ["ps5_rdesc", "ps5_rdesc_bt", "ps5_calibration_info",
          "ps5_firmware_info", "ps5_pairing_info"]

# Emitted verbatim into the generated file. The SPDX header has to be part of
# this template, not added afterwards, or regenerating drops it and `reuse lint`
# starts failing.
HEADER = '''# SPDX-FileCopyrightText: 2026 Mikalai Kaliaha
# SPDX-FileCopyrightText: 2021-2024 Games on Whales
#
# SPDX-License-Identifier: MIT

"""DualSense report descriptor and feature-report blobs.

Generated by tools/gen_ps5_data.py -- do not edit by hand.

Source: inputtino (https://github.com/games-on-whales/inputtino),
src/uhid/include/uhid/ps5.hpp, used under the MIT License:

    MIT License
    Copyright (c) 2021-2024 Games on Whales
    https://github.com/games-on-whales/

hid-playstation requests these feature reports while probing; without valid
replies it fails and no DualSense input device appears.
"""

# Feature report numbers requested by hid-playstation during probe.
CALIBRATION = 0x05
PAIRING_INFO = 0x09
FIRMWARE_INFO = 0x20

'''


def parse_array(text, name):
    match = re.search(
        rf"static constexpr unsigned char {name}\[\]\s*=\s*\{{(.*?)\}};",
        text, re.S)
    if not match:
        raise SystemExit(f"array {name} not found")
    body = re.sub(r"//[^\n]*", "", match.group(1))
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    values = []
    for token in body.split(","):
        token = token.strip()
        if not token:
            continue
        values.append(int(token, 0))
    return values


def render(name, values):
    lines = [f"{name.upper()} = bytes(["]
    for i in range(0, len(values), 12):
        chunk = ", ".join(f"0x{v:02X}" for v in values[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("])")
    lines.append(f"# {len(values)} bytes")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    text = open(sys.argv[1]).read()
    out = [HEADER]
    for name in ARRAYS:
        values = parse_array(text, name)
        out.append(render(name, values))
        out.append("")
        print(f"  {name}: {len(values)} bytes", file=sys.stderr)
    with open("flydigi/ps5_data.py", "w") as fh:
        fh.write("\n".join(out))
    print("wrote flydigi/ps5_data.py", file=sys.stderr)


if __name__ == "__main__":
    main()
